# Base configs
baseurl: "http://emrpictures.com"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "Photography by Enmanuel Rodriguez"
subtitle: "My lens make my story"
author: "Enmanuel Rodriguez"
bio: "I am a freelance professional photographer with an eye for nature, animals, and landscape images. "
publicise: 
web_design: "Aberod"
social_urls:

  